
##  Set the desired Root Path location for your own device here before you run the program:
#   Ensure the backslashes for Windows are changed to forward slashes
#   Eg:         C:\Users\Tim\Desktop\projects\ZZ__Interview_Assignments\file-system-app
#   becomes:    C:/Users/Tim/Desktop/projects/ZZ__Interview_Assignments/file-system-app
root_path=C:/Users/Tim/Desktop/projects/ZZ__Interview_Assignments/file-system-app/src


